version: 2

jobs:
  build:
    working_directory: ~/Documentation
    docker:
      - image: feedyard/circleci-markdown-agent
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: run tests
          command: 'invoke lint'